### PR TITLE
Added the last_update field to the layer documentation.

### PR DESCRIPTION
**Pull request by AntoJvlt**

### CODE REVIEW

**Comment by lonvia** [comment]
I wonder why https://nominatim.org/qa/#map=3.20/0.00/0.00&layer=addr_street_wrong_name doesn't have a date. All other layers work fine.

**Comment by AntoJvlt** [comment]
I can see the date on this layer, do I miss something?

**Comment by lonvia** [comment]
I see it in the layer.json but not on the side bar in the description. It looks like it is hidden under the next entry because the description text is too long:

nominatim-ui-hidden-description

The section with the date is where the area is marked yellow.

**Comment by AntoJvlt** [comment]
Oh ok right, it seems to be a problem on firefox as I don't have it on chrome. I will have a look at it later, thanks!

**Pull request merged**
