### PR TITLE
Svelte version

### PR DESCRIPTION
**Pull request by AntoJvlt**
The whole webapp was rewritten from React to Svelte.

### CODE REVIEW

**Comment by matkoniecz** [comment]
Not sure are you willing to comment on it - but why Svelte is so much better that rewrite is a good idea?

**Comment by AntoJvlt** [comment]
The reason is that Svelte is used on almost all the UI project related to nominatim, so we though it would be better to keep it also here. It was the good time to do it since we didn't have too much stuff to rewrite.

**Comment by lonvia** [comment]
This is now live on https://nominatim.org/qa/

**Comment by matkoniecz** [comment]
One thing that I noticed is significant lag before layer list will appear. About 2 seconds to see them, with wave animation displayed.

May be Svelte related or not.

**Comment by AntoJvlt** [comment]
This wave animation is displayed while the layers data are loaded from the server.

**Comment by matkoniecz** [comment]
Yes, but previously I have never seen it.

**Pull request merged**
